#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

use IO::Handle;

our $VERSION = '0.0';

my $infile = shift or die("Usage: ./transf <file.lcd>\n");

open(my $in, '<', $infile);
my $buf;
my $offs = 0;

while (read($in, $buf, 64)) {
	printf("Writing at %d: %s\n", $offs, unpack('h*', $buf));

	open(my $out, '>', '/dev/ttyACM0');
	print $out pack("cCa*", ord("d"), $offs, $buf);
	close($out);
	$offs++;
}
close($in);
